export const DISPLAY_OBJECTS = 'DISPLAY_OBJECTS';
export const CREATE_NEW_OBJECT = 'CREATE_NEW_OBJECT';
export const REMOVE_AN_OBJECT = 'REMOVE_AN_OBJECT';
export const UPDATE_OBJECT = 'UPDATE_OBJECT';

export const DISPLAY_INSTANCES = 'DISPLAY_INSTANCES';
export const REMOVE_AN_INSTANCE = 'REMOVE_AN_INSTANCE';
export const CREATE_NEW_INSTANCE = 'CREATE_NEW_INSTANCE';
export const UPDATE_INSTANCE = 'UPDATE_INSTANCE';
